from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Protocol


class Aria2Gateway(Protocol):
    async def add_uri(
        self, uris: list[str], options: Mapping[str, Any] | None = None
    ) -> str: ...

    async def add_torrent(
        self,
        torrent: str,
        uris: list[str] | None = None,
        options: Mapping[str, Any] | None = None,
    ) -> str: ...

    async def tell_status(self, gid: str) -> dict[str, Any]: ...
    async def tell_active(self) -> list[dict[str, Any]]: ...
    async def tell_waiting(
        self, offset: int = 0, num: int = 1000
    ) -> list[dict[str, Any]]: ...
    async def tell_stopped(
        self, offset: int = 0, num: int = 1000
    ) -> list[dict[str, Any]]: ...
    async def pause(self, gid: str) -> str: ...
    async def unpause(self, gid: str) -> str: ...
    async def change_option(
        self, gid: str, options: Mapping[str, Any]
    ) -> str: ...
    async def remove(self, gid: str) -> str: ...
    async def remove_download_result(self, gid: str) -> str: ...
    async def force_remove(self, gid: str) -> str: ...
    async def get_global_stat(self) -> dict[str, Any]: ...
    async def get_files(self, gid: str) -> list[dict[str, Any]]: ...
    async def get_uris(self, gid: str) -> list[dict[str, Any]]: ...
    async def get_peers(self, gid: str) -> list[dict[str, Any]]: ...
    async def get_servers(self, gid: str) -> list[dict[str, Any]]: ...
    async def get_version(self) -> dict[str, Any]: ...
    async def change_position(self, gid: str, pos: int, how: str) -> int: ...
